// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDoZlN4TP9pnYAUxRGAXJLA1oAOhzRcVjg',
    appId: '1:987009493612:web:d3b7f0db54da685214c649',
    messagingSenderId: '987009493612',
    projectId: 'prm393-project-857e1',
    authDomain: 'prm393-project-857e1.firebaseapp.com',
    storageBucket: 'prm393-project-857e1.firebasestorage.app',
    measurementId: 'G-QLFR7YVXV5',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCfm8V4VfG2S7R46-wKOAYfbHstMRildNo',
    appId: '1:987009493612:android:2fe88130d0d5a1e314c649',
    messagingSenderId: '987009493612',
    projectId: 'prm393-project-857e1',
    storageBucket: 'prm393-project-857e1.firebasestorage.app',
  );
}
